In [1]:
import numpy as np
import re
import itertools
from collections import Counter
import tensorflow as tf


In [11]:
def clean_str(string):
    """
    Tokenization/string cleaning for all datasets except for SST.
    Original taken from https://github.com/yoonkim/CNN_sentence/blob/master/process_data.py
    """
    # 不是特定字符都变成空格
    string = re.sub(r"[^A-Za-z0-9(),!?\'\`]", " ", string)
    # 加空格
    string = re.sub(r"\'s", " \'s", string)
    string = re.sub(r"\'ve", " \'ve", string)
    string = re.sub(r"n\'t", " n\'t", string)
    string = re.sub(r"\'re", " \'re", string)
    string = re.sub(r"\'d", " \'d", string)
    string = re.sub(r"\'ll", " \'ll", string)
    string = re.sub(r",", " , ", string)
    string = re.sub(r"!", " ! ", string)
    string = re.sub(r"\(", " \( ", string)
    string = re.sub(r"\)", " \) ", string)
    string = re.sub(r"\?", " \? ", string)
    # 匹配2个或多个空白字符变成一个" "空格
    string = re.sub(r"\s{2,}", " ", string)
    # 去掉句子首尾的空白符，再转小写
    return string.strip().lower()

positive_examples = ['the rock is destined to be the 21st century',
                    'effective but too-tepid biopic',
                    'if you sometimes like to go to the movies to have fun']
positive_examples = [s.strip() for s in positive_examples]
negative_examples=['the film provides some great insight into the neurotic mindset',
                  'take care of my cat offers a refreshingly']
negative_examples = [s.strip() for s in negative_examples]
x_text = positive_examples + negative_examples
print(x_text)
x_text = [clean_str(sent) for sent in x_text]

['the rock is destined to be the 21st century', 'effective but too-tepid biopic', 'if you sometimes like to go to the movies to have fun', 'the film provides some great insight into the neurotic mindset', 'take care of my cat offers a refreshingly']
['the rock is destined to be the 21st century', 'effective but too tepid biopic', 'if you sometimes like to go to the movies to have fun', 'the film provides some great insight into the neurotic mindset', 'take care of my cat offers a refreshingly']


In [25]:
positive_labels = [[0, 1] for _ in positive_examples]
negative_labels = [[1, 0] for _ in negative_examples]
print(positive_labels)
y = np.concatenate([positive_labels, negative_labels], 0)
print(y)

[[0, 1], [0, 1], [0, 1]]
[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]]


In [23]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.concatenate((a,b),axis=0)
d = np.concatenate((a,b.T),axis = 1)
e = np.concatenate([a,b],0)
print(c)
print(d)
print(e)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[[1 2]
 [3 4]
 [5 6]]


In [26]:
string1 = "the movie's ripe , enrapturing beauty will tempt those willing to probe its inscrutable mysteries! "
string2 = clean_str(string1)
print(string2)

the movie 's ripe , enrapturing beauty will tempt those willing to probe its inscrutable mysteries !


In [33]:
document_len = [len(x.split(" ")) for x in x_text]
print(document_len)
max_len = max(document_len)
print(max_len)

[9, 5, 12, 10, 8]
12


In [36]:
from tensorflow.contrib import learn

In [57]:
vocab = learn.preprocessing.VocabularyProcessor(max_len)
#将列表转换为数组
x = np.array(list(vocab.fit_transform(x_text)))
print(x)

[[ 1  2  3  4  5  6  1  7  8  0  0  0]
 [ 9 10 11 12 13  0  0  0  0  0  0  0]
 [14 15 16 17  5 18  5  1 19  5 20 21]
 [ 1 22 23 24 25 26 27  1 28 29  0  0]
 [30 31 32 33 34 35 36 37  0  0  0  0]]


In [41]:
import random
list1 = [20, 16, 10, 5]
random.shuffle(list1)
print("随机排序列表 : ",  list1)

random.shuffle(list1)
print("随机排序列表 : ",  list1)

随机排序列表 :  [20, 16, 10, 5]
随机排序列表 :  [10, 20, 5, 16]


In [47]:
import numpy as np
from numpy.random import rand
np.random.seed(3)
a = rand(5)
print("first:",a)

first: [0.5507979  0.70814782 0.29090474 0.51082761 0.89294695]


In [49]:
np.random.seed(3)
a = rand(5)
print("second:",a)

second: [0.5507979  0.70814782 0.29090474 0.51082761 0.89294695]


In [50]:
#数字0-4排序
b = np.random.permutation(5)
print(b)

[0 4 1 3 2]


In [51]:
#list排序
c = np.random.permutation([1,2,3,4,5,6,7,8,9,0])
print(c)

[4 9 3 2 0 5 1 7 8 6]


In [52]:
aa = np.arange(3)
print(aa)

[0 1 2]


In [53]:
bb = np.arange(3,9)
print(bb)

[3 4 5 6 7 8]


In [54]:
cc = np.arange(1,10,2)#起点1，终点10，步长2
print(cc)

[1 3 5 7 9]


In [60]:
print(x)
print(y)
print("______")
np.random.seed(10)
shuffle_indices1 = np.random.permutation(np.arange(len(y)))
x_shuffled = x[shuffle_indices1]
y_shuffled = y[shuffle_indices1]
print(x_shuffled)
print(y_shuffled)

[[ 1  2  3  4  5  6  1  7  8  0  0  0]
 [ 9 10 11 12 13  0  0  0  0  0  0  0]
 [14 15 16 17  5 18  5  1 19  5 20 21]
 [ 1 22 23 24 25 26 27  1 28 29  0  0]
 [30 31 32 33 34 35 36 37  0  0  0  0]]
[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]]
______
[[14 15 16 17  5 18  5  1 19  5 20 21]
 [ 1 22 23 24 25 26 27  1 28 29  0  0]
 [ 1  2  3  4  5  6  1  7  8  0  0  0]
 [30 31 32 33 34 35 36 37  0  0  0  0]
 [ 9 10 11 12 13  0  0  0  0  0  0  0]]
[[0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]]


In [63]:
import tensorflow as tf
with tf.Session() as sess:
    print(sess.run(tf.random_uniform(
        (6,6), minval=-0.5,
        maxval=0.5, dtype=tf.float32)))

[[-0.08788133  0.22054613 -0.03172755 -0.13382006  0.26269603  0.35440767]
 [ 0.09093058  0.12063205 -0.3468814  -0.00612164 -0.47694886  0.31444407]
 [-0.35818386  0.23495948  0.4968568  -0.13550162 -0.29231262 -0.49774373]
 [-0.36301184  0.15901637  0.02170622 -0.29145586 -0.2537732   0.20505822]
 [ 0.06371689  0.07469189 -0.08913267  0.01038587 -0.28714263  0.34437072]
 [-0.43197167 -0.15391958  0.3788265  -0.10389376 -0.47904682  0.3731209 ]]


In [2]:
#enumerate() 函数用于将一个可遍历的数据对象(如列表、元组或字符串)组合为一个索引序列，同时列出数据和数据下标
data1 = ['how','are','you']
print(list(enumerate(data1)))

[(0, 'how'), (1, 'are'), (2, 'you')]


In [8]:
#shape
arr1= np.array([1,2,3,4,5,6,7,8])
print(arr1)
arr2 = arr1.reshape(2,4)
print(arr2)
arr3 = arr1.reshape(2,2,2)
print(arr3)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
%run ./train.py


Loading data...
Instructions for updating:
Please use tensorflow/transform or tf.data.


W1021 16:35:11.217345  6356 deprecation.py:323] From D:\Tensorflow\20201014cnn-text-classification\train.py:82: VocabularyProcessor.__init__ (from tensorflow.contrib.learn.python.learn.preprocessing.text) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tensorflow/transform or tf.data.


Instructions for updating:
Please use tensorflow/transform or tf.data.


W1021 16:35:11.219324  6356 deprecation.py:323] From D:\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\preprocessing\text.py:154: CategoricalVocabulary.__init__ (from tensorflow.contrib.learn.python.learn.preprocessing.categorical_vocabulary) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tensorflow/transform or tf.data.


Instructions for updating:
Please use tensorflow/transform or tf.data.


W1021 16:35:11.221326  6356 deprecation.py:323] From D:\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\preprocessing\text.py:170: tokenizer (from tensorflow.contrib.learn.python.learn.preprocessing.text) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tensorflow/transform or tf.data.


Vocabulary Size: 18758
Train/Dev split: 9596/1066



W1021 16:35:11.922923  6356 deprecation_wrapper.py:119] From D:\Tensorflow\20201014cnn-text-classification\train.py:115: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.



W1021 16:35:11.924921  6356 deprecation_wrapper.py:119] From D:\Tensorflow\20201014cnn-text-classification\train.py:118: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



W1021 16:35:16.226038  6356 deprecation_wrapper.py:119] From D:\Tensorflow\20201014cnn-text-classification\text_cnn.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.



W1021 16:35:16.251018  6356 deprecation_wrapper.py:119] From D:\Tensorflow\20201014cnn-text-classification\text_cnn.py:38: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



W1021 16:35:16.317990  6356 deprecation_wrapper.py:119] From D:\Tensorflow\20201014cnn-text-classification\text_cnn.py:57: The name tf.truncated_normal is deprecated. Please use tf.random.truncated_normal instead.



W1021 16:35:16.379949  6356 deprecation_wrapper.py:119] From D:\Tensorflow\20201014cnn-text-classification\text_cnn.py:78: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.



Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


W1021 16:35:16.487883  6356 deprecation.py:506] From D:\Tensorflow\20201014cnn-text-classification\text_cnn.py:97: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


W1021 16:35:16.558839  6356 deprecation_wrapper.py:119] From D:\Tensorflow\20201014cnn-text-classification\text_cnn.py:113: The name tf.nn.xw_plus_b is deprecated. Please use tf.compat.v1.nn.xw_plus_b instead.



Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



W1021 16:35:16.571832  6356 deprecation.py:323] From D:\Tensorflow\20201014cnn-text-classification\text_cnn.py:119: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



W1021 16:35:16.671775  6356 deprecation_wrapper.py:119] From D:\Tensorflow\20201014cnn-text-classification\train.py:135: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.



W1021 16:35:17.141525  6356 deprecation_wrapper.py:119] From D:\Tensorflow\20201014cnn-text-classification\train.py:146: The name tf.summary.histogram is deprecated. Please use tf.compat.v1.summary.histogram instead.



INFO:tensorflow:Summary name embedding/W:0/grad/hist is illegal; using embedding/W_0/grad/hist instead.


I1021 16:35:17.143507  6356 summary_op_util.py:66] Summary name embedding/W:0/grad/hist is illegal; using embedding/W_0/grad/hist instead.


W1021 16:35:17.161515  6356 deprecation_wrapper.py:119] From D:\Tensorflow\20201014cnn-text-classification\train.py:148: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.



INFO:tensorflow:Summary name embedding/W:0/grad/sparsity is illegal; using embedding/W_0/grad/sparsity instead.


I1021 16:35:17.213466  6356 summary_op_util.py:66] Summary name embedding/W:0/grad/sparsity is illegal; using embedding/W_0/grad/sparsity instead.


INFO:tensorflow:Summary name conv-maxpool-3/W:0/grad/hist is illegal; using conv-maxpool-3/W_0/grad/hist instead.


I1021 16:35:17.220464  6356 summary_op_util.py:66] Summary name conv-maxpool-3/W:0/grad/hist is illegal; using conv-maxpool-3/W_0/grad/hist instead.


INFO:tensorflow:Summary name conv-maxpool-3/W:0/grad/sparsity is illegal; using conv-maxpool-3/W_0/grad/sparsity instead.


I1021 16:35:17.275430  6356 summary_op_util.py:66] Summary name conv-maxpool-3/W:0/grad/sparsity is illegal; using conv-maxpool-3/W_0/grad/sparsity instead.


INFO:tensorflow:Summary name conv-maxpool-3/b:0/grad/hist is illegal; using conv-maxpool-3/b_0/grad/hist instead.


I1021 16:35:17.287427  6356 summary_op_util.py:66] Summary name conv-maxpool-3/b:0/grad/hist is illegal; using conv-maxpool-3/b_0/grad/hist instead.


INFO:tensorflow:Summary name conv-maxpool-3/b:0/grad/sparsity is illegal; using conv-maxpool-3/b_0/grad/sparsity instead.


I1021 16:35:17.357383  6356 summary_op_util.py:66] Summary name conv-maxpool-3/b:0/grad/sparsity is illegal; using conv-maxpool-3/b_0/grad/sparsity instead.


INFO:tensorflow:Summary name conv-maxpool-4/W:0/grad/hist is illegal; using conv-maxpool-4/W_0/grad/hist instead.


I1021 16:35:17.364379  6356 summary_op_util.py:66] Summary name conv-maxpool-4/W:0/grad/hist is illegal; using conv-maxpool-4/W_0/grad/hist instead.


INFO:tensorflow:Summary name conv-maxpool-4/W:0/grad/sparsity is illegal; using conv-maxpool-4/W_0/grad/sparsity instead.


I1021 16:35:17.416347  6356 summary_op_util.py:66] Summary name conv-maxpool-4/W:0/grad/sparsity is illegal; using conv-maxpool-4/W_0/grad/sparsity instead.


INFO:tensorflow:Summary name conv-maxpool-4/b:0/grad/hist is illegal; using conv-maxpool-4/b_0/grad/hist instead.


I1021 16:35:17.425345  6356 summary_op_util.py:66] Summary name conv-maxpool-4/b:0/grad/hist is illegal; using conv-maxpool-4/b_0/grad/hist instead.


INFO:tensorflow:Summary name conv-maxpool-4/b:0/grad/sparsity is illegal; using conv-maxpool-4/b_0/grad/sparsity instead.


I1021 16:35:17.478315  6356 summary_op_util.py:66] Summary name conv-maxpool-4/b:0/grad/sparsity is illegal; using conv-maxpool-4/b_0/grad/sparsity instead.


INFO:tensorflow:Summary name conv-maxpool-5/W:0/grad/hist is illegal; using conv-maxpool-5/W_0/grad/hist instead.


I1021 16:35:17.486316  6356 summary_op_util.py:66] Summary name conv-maxpool-5/W:0/grad/hist is illegal; using conv-maxpool-5/W_0/grad/hist instead.


INFO:tensorflow:Summary name conv-maxpool-5/W:0/grad/sparsity is illegal; using conv-maxpool-5/W_0/grad/sparsity instead.


I1021 16:35:17.541277  6356 summary_op_util.py:66] Summary name conv-maxpool-5/W:0/grad/sparsity is illegal; using conv-maxpool-5/W_0/grad/sparsity instead.


INFO:tensorflow:Summary name conv-maxpool-5/b:0/grad/hist is illegal; using conv-maxpool-5/b_0/grad/hist instead.


I1021 16:35:17.547274  6356 summary_op_util.py:66] Summary name conv-maxpool-5/b:0/grad/hist is illegal; using conv-maxpool-5/b_0/grad/hist instead.


INFO:tensorflow:Summary name conv-maxpool-5/b:0/grad/sparsity is illegal; using conv-maxpool-5/b_0/grad/sparsity instead.


I1021 16:35:17.598244  6356 summary_op_util.py:66] Summary name conv-maxpool-5/b:0/grad/sparsity is illegal; using conv-maxpool-5/b_0/grad/sparsity instead.


INFO:tensorflow:Summary name W:0/grad/hist is illegal; using W_0/grad/hist instead.


I1021 16:35:17.607241  6356 summary_op_util.py:66] Summary name W:0/grad/hist is illegal; using W_0/grad/hist instead.


INFO:tensorflow:Summary name W:0/grad/sparsity is illegal; using W_0/grad/sparsity instead.


I1021 16:35:17.652215  6356 summary_op_util.py:66] Summary name W:0/grad/sparsity is illegal; using W_0/grad/sparsity instead.


INFO:tensorflow:Summary name output/b:0/grad/hist is illegal; using output/b_0/grad/hist instead.


I1021 16:35:17.659210  6356 summary_op_util.py:66] Summary name output/b:0/grad/hist is illegal; using output/b_0/grad/hist instead.


INFO:tensorflow:Summary name output/b:0/grad/sparsity is illegal; using output/b_0/grad/sparsity instead.


I1021 16:35:17.704184  6356 summary_op_util.py:66] Summary name output/b:0/grad/sparsity is illegal; using output/b_0/grad/sparsity instead.


W1021 16:35:17.710181  6356 deprecation_wrapper.py:119] From D:\Tensorflow\20201014cnn-text-classification\train.py:152: The name tf.summary.merge is deprecated. Please use tf.compat.v1.summary.merge instead.



Writing to D:\Tensorflow\20201014cnn-text-classification\runs\1603269317




W1021 16:35:17.727169  6356 deprecation_wrapper.py:119] From D:\Tensorflow\20201014cnn-text-classification\train.py:171: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.



W1021 16:35:20.781006  6356 deprecation_wrapper.py:119] From D:\Tensorflow\20201014cnn-text-classification\train.py:185: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.



num_batches_per_epoch: 150
2020-10-21T16:35:26.266871: step 1, loss 0.790037, acc 0.5



W1021 16:35:26.279876  6356 deprecation_wrapper.py:119] From D:\Tensorflow\20201014cnn-text-classification\train.py:241: The name tf.train.global_step is deprecated. Please use tf.compat.v1.train.global_step instead.



2020-10-21T16:35:26.440767: step 2, loss 0.717555, acc 0.578125
2020-10-21T16:35:26.594680: step 3, loss 0.83759, acc 0.4375
2020-10-21T16:35:26.749591: step 4, loss 0.78603, acc 0.453125
2020-10-21T16:35:26.898507: step 5, loss 0.789444, acc 0.515625
2020-10-21T16:35:27.044421: step 6, loss 0.841226, acc 0.40625
2020-10-21T16:35:27.178365: step 7, loss 0.799345, acc 0.46875
2020-10-21T16:35:27.334260: step 8, loss 0.786842, acc 0.5
2020-10-21T16:35:27.492167: step 9, loss 0.87547, acc 0.34375
2020-10-21T16:35:27.706046: step 10, loss 0.726632, acc 0.546875
2020-10-21T16:35:27.867952: step 11, loss 0.777425, acc 0.484375
2020-10-21T16:35:28.013868: step 12, loss 0.897218, acc 0.375
2020-10-21T16:35:28.161785: step 13, loss 0.727986, acc 0.5625
2020-10-21T16:35:28.315696: step 14, loss 0.822473, acc 0.46875
2020-10-21T16:35:28.453617: step 15, loss 0.772765, acc 0.515625
2020-10-21T16:35:28.615525: step 16, loss 0.870324, acc 0.40625
2020-10-21T16:35:28.770436: step 17, loss 0.812414, a

2020-10-21T16:35:47.410775: step 128, loss 0.720893, acc 0.578125
2020-10-21T16:35:47.551692: step 129, loss 0.73472, acc 0.515625
2020-10-21T16:35:47.696629: step 130, loss 0.717038, acc 0.546875
2020-10-21T16:35:47.839529: step 131, loss 0.703899, acc 0.59375
2020-10-21T16:35:47.985444: step 132, loss 0.712096, acc 0.5625
2020-10-21T16:35:48.127363: step 133, loss 0.718481, acc 0.578125
2020-10-21T16:35:48.280277: step 134, loss 0.800717, acc 0.484375
2020-10-21T16:35:48.422214: step 135, loss 0.755092, acc 0.53125
2020-10-21T16:35:48.568114: step 136, loss 0.837414, acc 0.453125
2020-10-21T16:35:48.715027: step 137, loss 0.721297, acc 0.53125
2020-10-21T16:35:48.871938: step 138, loss 0.671364, acc 0.625
2020-10-21T16:35:49.017854: step 139, loss 0.731661, acc 0.5625
2020-10-21T16:35:49.158773: step 140, loss 0.713837, acc 0.578125
2020-10-21T16:35:49.303694: step 141, loss 0.740718, acc 0.546875
2020-10-21T16:35:49.450608: step 142, loss 0.783846, acc 0.5
2020-10-21T16:35:49.604520

2020-10-21T16:36:09.272269: step 252, loss 0.667265, acc 0.609375
2020-10-21T16:36:09.417186: step 253, loss 0.701038, acc 0.609375
2020-10-21T16:36:09.564102: step 254, loss 0.645345, acc 0.609375
2020-10-21T16:36:09.736008: step 255, loss 0.689312, acc 0.609375
2020-10-21T16:36:09.908904: step 256, loss 0.652463, acc 0.640625
2020-10-21T16:36:10.062816: step 257, loss 0.810035, acc 0.46875
2020-10-21T16:36:10.208734: step 258, loss 0.630291, acc 0.703125
2020-10-21T16:36:10.356648: step 259, loss 0.720808, acc 0.53125
2020-10-21T16:36:10.505568: step 260, loss 0.66331, acc 0.59375
2020-10-21T16:36:10.685461: step 261, loss 0.622262, acc 0.671875
2020-10-21T16:36:10.835375: step 262, loss 0.70979, acc 0.5625
2020-10-21T16:36:10.975298: step 263, loss 0.695807, acc 0.609375
2020-10-21T16:36:11.113216: step 264, loss 0.703226, acc 0.5625
2020-10-21T16:36:11.276123: step 265, loss 0.559096, acc 0.734375
2020-10-21T16:36:11.442027: step 266, loss 0.654432, acc 0.640625
2020-10-21T16:36:11

2020-10-21T16:36:28.875057: step 376, loss 0.610799, acc 0.6875
2020-10-21T16:36:29.028968: step 377, loss 0.64171, acc 0.671875
2020-10-21T16:36:29.170887: step 378, loss 0.596647, acc 0.71875
2020-10-21T16:36:29.317803: step 379, loss 0.664435, acc 0.609375
2020-10-21T16:36:29.463719: step 380, loss 0.595857, acc 0.71875
2020-10-21T16:36:29.605639: step 381, loss 0.639208, acc 0.703125
2020-10-21T16:36:29.750557: step 382, loss 0.580946, acc 0.71875
2020-10-21T16:36:29.891475: step 383, loss 0.640682, acc 0.65625
2020-10-21T16:36:30.037393: step 384, loss 0.735738, acc 0.53125
2020-10-21T16:36:30.181311: step 385, loss 0.612445, acc 0.671875
2020-10-21T16:36:30.332226: step 386, loss 0.562915, acc 0.765625
2020-10-21T16:36:30.470146: step 387, loss 0.561157, acc 0.75
2020-10-21T16:36:30.619063: step 388, loss 0.697891, acc 0.578125
2020-10-21T16:36:30.760979: step 389, loss 0.582159, acc 0.734375
2020-10-21T16:36:30.912892: step 390, loss 0.605693, acc 0.703125
2020-10-21T16:36:31.04

2020-10-21T16:36:48.736697: step 499, loss 0.557417, acc 0.765625
2020-10-21T16:36:48.889609: step 500, loss 0.677931, acc 0.625

Evaluation:
2020-10-21T16:36:49.063511: step 500, loss 0.673432, acc 0.603189

Saved model checkpoint to D:\Tensorflow\20201014cnn-text-classification\runs\1603269317\checkpoints\model-500

2020-10-21T16:36:50.798707: step 501, loss 0.59738, acc 0.703125
2020-10-21T16:36:50.941625: step 502, loss 0.65708, acc 0.609375
2020-10-21T16:36:51.080545: step 503, loss 0.59053, acc 0.71875
2020-10-21T16:36:51.233458: step 504, loss 0.581819, acc 0.671875
2020-10-21T16:36:51.379375: step 505, loss 0.594005, acc 0.703125
2020-10-21T16:36:51.527290: step 506, loss 0.672625, acc 0.640625
2020-10-21T16:36:51.672207: step 507, loss 0.59209, acc 0.71875
2020-10-21T16:36:51.824120: step 508, loss 0.561726, acc 0.75
2020-10-21T16:36:51.969038: step 509, loss 0.577094, acc 0.71875
2020-10-21T16:36:52.120953: step 510, loss 0.578627, acc 0.703125
2020-10-21T16:36:52.265867: ste

W1021 16:37:06.778567  6356 deprecation.py:323] From D:\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py:960: remove_checkpoint (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to delete files with this prefix.


Saved model checkpoint to D:\Tensorflow\20201014cnn-text-classification\runs\1603269317\checkpoints\model-600

2020-10-21T16:37:07.825987: step 601, loss 0.543167, acc 0.75
2020-10-21T16:37:07.974882: step 602, loss 0.567821, acc 0.75
2020-10-21T16:37:08.115802: step 603, loss 0.603045, acc 0.6875
2020-10-21T16:37:08.263717: step 604, loss 0.542852, acc 0.765625
2020-10-21T16:37:08.406636: step 605, loss 0.554855, acc 0.765625
2020-10-21T16:37:08.558569: step 606, loss 0.575347, acc 0.71875
2020-10-21T16:37:08.702468: step 607, loss 0.485029, acc 0.8125
2020-10-21T16:37:08.868374: step 608, loss 0.57756, acc 0.71875
2020-10-21T16:37:09.005294: step 609, loss 0.582805, acc 0.6875
2020-10-21T16:37:09.151211: step 610, loss 0.53196, acc 0.75
2020-10-21T16:37:09.289151: step 611, loss 0.588312, acc 0.703125
2020-10-21T16:37:09.439048: step 612, loss 0.484267, acc 0.8125
2020-10-21T16:37:09.590958: step 613, loss 0.51753, acc 0.78125
2020-10-21T16:37:09.752866: step 614, loss 0.519349, acc 

KeyboardInterrupt: 